---
title: "UFC Data Exploration"
author: "Isaac Amouzou"
format: html
editor: visual
---

## Libraries

```{r}
library(tidyverse)
```

## Check data structure and missing

```{r}
data <- read_csv("Data/data.csv")
```

Variables are stored as numeric or categorical but some could be logical.

```{r}

#numeric columns with 5 or fewer unique values are casted as factor
data <- data %>%
  mutate(across(where(is.numeric), ~ if(length(unique(.)) <= 5) factor(.) else .))

summary_types <- sapply(data, class)

cat("Number of factor columns:", sum(summary_types == "factor"), "\n")
cat("Number of numeric columns:", sum(summary_types %in% c("numeric", "integer")), "\n")
cat("Number of character columns:", sum(summary_types == "character"), "\n")
```

```{r}
perc.missing <- sapply(data,
                          function(x){
                            mean(is.na(x)) * 100})

missing_df <- data.frame(
  perc_missing = perc.missing) %>% 
  arrange(desc(perc_missing))
head(missing_df)  
```

Nothing more than 23.73586% missing so this is good.

```{r}
na.omit(data) %>% dim()

```

3890 rows when missing is removed

## Numeric relationships

```{r}
corr_matrix <- data %>%
  select(where(is.numeric)) %>%
  cor(use = "pairwise.complete.obs")

high_corr <- as.data.frame(as.table(corr_matrix)) %>%
  filter(Var1 != Var2, abs(Freq) > 0.6) %>%
  arrange(desc(abs(Freq)))

dim(high_corr)
```

A lot of variables with decent to high correlation variables

# TODO

### 
